import { describe, expect, it } from 'vitest'
import { parseVtt } from '@/features/videos/subtitles'

describe('FT-019 VTT parser', () => {
  it('parses provider-like VTT variants into ordered segments', () => {
    const input = [
      '\uFEFFWEBVTT - Kind: captions',
      '',
      'NOTE generated by provider',
      'ignore this block',
      '',
      '1',
      '00:00.000 --> 00:02.000 align:start line:0%',
      '<v Speaker>Hello</v>',
      '<c.green>world</c>',
      '',
      'chapter-2',
      '00:02.500 --> 00:04.000',
      'Second line',
      '',
      '02:03.456 --> 02:05.000',
      'Short format cue',
      '',
    ].join('\n')

    const result = parseVtt(input)

    expect(result.status).toBe('ok')
    expect(result.errors).toEqual([])
    expect(result.segments).toEqual([
      { start: 0, end: 2, text: 'Hello\nworld' },
      { start: 2.5, end: 4, text: 'Second line' },
      { start: 123.456, end: 125, text: 'Short format cue' },
    ])
  })

  it('returns partial when one cue is broken but others are valid', () => {
    const input = [
      'WEBVTT',
      '',
      '00:00.000 --> 00:01.000',
      'First cue',
      '',
      'broken cue',
      '',
      '00:02.000 --> 00:03.000',
      'Last cue',
      '',
    ].join('\n')

    const result = parseVtt(input)

    expect(result.status).toBe('partial')
    expect(result.segments).toEqual([
      { start: 0, end: 1, text: 'First cue' },
      { start: 2, end: 3, text: 'Last cue' },
    ])
    expect(result.errors).toEqual([{ line: 6, reason: 'Ожидалась строка таймкода cue.' }])
  })

  it('returns invalid when WEBVTT header is missing', () => {
    const result = parseVtt('00:00.000 --> 00:01.000\nNo header\n')

    expect(result).toEqual({
      status: 'invalid',
      segments: [],
      errors: [{ line: 1, reason: 'Файл должен начинаться с заголовка WEBVTT.' }],
    })
  })
})
